### ISSUE TITLE
Fabric 1.18.2

### ISSUE THREAD

**Issue by ardissaps** [WForst-Breeze/glassplus-developerkit#3]
Would you please? thanks

**Comment by WForst-Breeze** [comment]
Thanks for your issue!
In the future, I will start porting this mod to Fabric 1.18.2. But now I prefer to perfect the 1.19 version, sorry for that. So please wait 😉

**Comment by WForst-Breeze** [comment]
Thanks for your issue!
In the future, I will start porting this mod to Fabric 1.18.2. But now I'd rather improve the 1.19 version, I'm sorry about that. So please wait 😉

**Comment by WForst-Breeze** [comment]
Thanks for your issue!
In the future, I will start porting this mod to Fabric 1.18.2. But now I'd rather improve the versions for 1.19, I'm sorry about that. So please wait 😉

**Comment by WForst-Breeze** [comment]
Even though I have tried various methods I can, I am sorry that this mod will not support fabric 1.18.2. Because the mcreator [plugin](https://github.com/Goldorion/Fabric-Generator-MCreator/issues/228) I use does not support version 1.18.2.

**Comment by ScandiumMascot** [comment]
Sorry, this feature cannot be implemented. Thank you for your issue.
